# Page title
page_title: "ReadHero" # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: "6450433398" # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: "us" # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: "https://apps.apple.com/us/app/readhero-tbr-book-tracker/id6450433398"

app_icon: "" # Automatically populates
app_name: "ReadHero - TBR Book Tracker" # Automatically populated from iOS ID
app_price: "Remember books by taking notes"
app_description: "The #1 Book Tracker üìö‚ú® Loved by thousands!Ô∏è"

enable_smart_app_banner: true

#Appstore Performance Metrics
downloads: "20.000+"
ratings: "364+"
rating_avg: "4.7"

# Information About Yourself
your_name: "Dennis Sima"
your_link: "https://at.linkedin.com/in/dennis-sima"
your_city: "Austria üá¶üáπ & Germany üá©üá™"
email_address: "readheroapp@gmail.com"
linkedin_company: "readheroapp"
instagram_username: "readheroapp"
twitter_username: "readheroapp"

# Feature List
features:
  - title: "Organize Your Library"
    description: "Add books manually, by barcode, or search over a million titles. Track TBR and finished books in one place."
    fontawesome_icon_name: "book"

  - title: "Track Your Reading Progress"
    description: "Forget bookmarks‚Äîtrack your page progress for each book directly in the app."
    fontawesome_icon_name: "chart-line"

  - title: "Take Powerful Notes"
    description: "Boost retention by writing notes while reading. Review them anytime‚Äîeven years later."
    fontawesome_icon_name: "sticky-note"

  - title: "Personalized Ratings"
    description: "Rate and reflect on books to strengthen memory and improve future reading decisions."
    fontawesome_icon_name: "star-half-alt"

  - title: "Group Your Books"
    description: "Create custom groups to organize books like playlists‚Äîfavorites, genre, authors, and more."
    fontawesome_icon_name: "folder-open"

  - title: "View Reading Stats"
    description: "Get insights on how long you read, what you‚Äôve read, and your overall reading habits."
    fontawesome_icon_name: "chart-pie"

  - title: "Sync with iCloud"
    description: "Keep your books, reading status, and notes‚Äîsafely synced across all your iOS devices."
    fontawesome_icon_name: "sync"

  - title: "Home Screen Widgets"
    description: "Add widgets to your iOS home screen for quick access to your current read or reading stats."
    fontawesome_icon_name: "arrow-alt-circle-down"

  - title: "Goodreads Import"
    description: "Import your Goodreads library and reading history to start tracking in your new favorite app."
    fontawesome_icon_name: "book"


# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: "assets/header-books.jpg"
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: "ready" # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"
link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

sass:
  style: :compressed

exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

markdown: kramdown
